### ISSUE TITLE
视图第一列可以不固定住吗？

### ISSUE THREAD

**Issue by wyk190576528** [ReverseScale/RSExcelDemo#1]

**Comment by ReverseScale** [comment]
这个Demo只是一种思路的记录，可能性能存在问题，不推荐正式使用。💩

如果需求不是特别相似，第一列如果要一起动的话，还是使用CollectionView更直接些吧
如果要用轮子，推荐这个吧，https://github.com/RmondJone/ExcelView <https://github.com/RmondJone/ExcelView>

设置一下就应该能满足你的要求。
excelView.isLockFristColumn=YES;
