### ISSUE TITLE
可以获取到控件加载完之后的高度么？用于复杂页面的搭建。

### ISSUE THREAD

**Issue by SuperGuo751** [ReverseScale/RSExcelDemo#2]
自适应高度，之后可以回调一个最后高度的方法么？

**Comment by SuperGuo751** [comment]
知道了 可以在RSReportView的layoutSubviews写一个代理或者回调方法把contentHeight传回去

**Comment by ReverseScale** [comment]
妙啊，欢迎一起来维护项目哦 👨🏿‍💻👨🏻‍💻👨🏼‍💻👩🏿‍💻👩🏻‍💻👩🏼‍💻
